services:
  slant:
    # You can use either 'slant_cpu_v1_0' or 'slant_cpu_v1_1' images
    image: seercle/slant_cpu_v1_0
    container_name: slant_cpu_v1_0
    environment:
      - INTERVAL_SECONDS=2
    volumes:
      - ../../datasets/RAIDERS_FMRI:/CUSTOM_INPUTS
      - ./OUTPUTS:/CUSTOM_OUTPUTS
